import type { MenuItem, Order, Review } from '@/types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Risotto',
    price: 24.5,
    category: 'Main Course',
    description: 'Creamy Arborio rice cooked with black truffle puree, savory Parmesan cheese, and a hint of white wine for a rich, earthy flavor.',
    imageUrl: 'https://placehold.co/150x150.png',
    imageHint: 'truffle risotto plate',
    inStock: true,
    customizable: false,
  },
  {
    id: '2',
    name: 'Seared Scallops',
    price: 18.0,
    category: 'Appetizer',
    description: 'Perfectly pan-seared jumbo scallops, served with a zesty lemon-butter sauce, capers, and garnished with fresh parsley.',
    imageUrl: 'https://placehold.co/150x150.png',
    imageHint: 'seared scallops dish',
    inStock: true,
    customizable: false,
  },
  {
    id: '3',
    name: 'Chocolate Lava Cake',
    price: 12.0,
    category: 'Dessert',
    description: 'A decadent, warm chocolate cake with a gooey, molten chocolate center. Served with a scoop of premium vanilla bean ice cream and a raspberry coulis.',
    imageUrl: 'https://placehold.co/150x150.png',
    imageHint: 'chocolate lava cake',
    inStock: false,
    customizable: false,
  },
  {
    id: '4',
    name: 'Classic Mojito',
    price: 14.0,
    category: 'Beverage',
    description: 'A crisp and refreshing cocktail made with high-quality white rum, freshly squeezed lime juice, muddled mint leaves, and a splash of soda water.',
    imageUrl: 'https://placehold.co/150x150.png',
    imageHint: 'mojito cocktail glass',
    inStock: true,
    customizable: true,
  },
  {
    id: '5',
    name: 'Burrata Caprese',
    price: 16.5,
    category: 'Appetizer',
    description: 'Creamy, fresh burrata cheese on a bed of colorful heirloom tomatoes, topped with fresh basil leaves and a drizzle of aged balsamic glaze.',
    imageUrl: 'https://placehold.co/150x150.png',
    imageHint: 'caprese salad plate',
    inStock: true,
    customizable: false,
  },
  {
    id: '6',
    name: 'Filet Mignon',
    price: 45.0,
    category: 'Main Course',
    description: 'An 8oz center-cut filet mignon, expertly grilled to your preference. Served with tender-crisp asparagus and creamy garlic mashed potatoes.',
    imageUrl: 'https://placehold.co/150x150.png',
    imageHint: 'filet mignon steak',
    inStock: true,
    customizable: true,
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    table: 3,
    items: [
      { id: '1', name: 'Truffle Risotto', quantity: 1, price: 24.5 },
      { id: '2', name: 'Seared Scallops', quantity: 1, price: 18.0 },
      { id: '4', name: 'Classic Mojito', quantity: 2, price: 14.0 },
    ],
    total: 70.5,
    status: 'Preparing',
  },
  {
    id: 'ORD-002',
    table: 5,
    items: [
      { id: '6', name: 'Filet Mignon', quantity: 2, price: 45.0 },
      { id: '5', name: 'Burrata Caprese', quantity: 1, price: 16.5 },
    ],
    total: 106.5,
    status: 'Pending',
  },
  {
    id: 'ORD-003',
    table: 1,
    items: [{ id: '3', name: 'Chocolate Lava Cake', quantity: 1, price: 12.0 }],
    total: 12.0,
    status: 'Completed',
  },
  {
    id: 'ORD-004',
    table: 8,
    items: [{ id: '1', name: 'Truffle Risotto', quantity: 1, price: 24.5 }],
    total: 24.5,
    status: 'Pending',
  },
  {
    id: 'ORD-005',
    table: 3,
    items: [{ id: '2', name: 'Seared Scallops', quantity: 1, price: 18.0 }],
    total: 18.0,
    status: 'Cancelled',
  },
];

export const reviews: Review[] = [
  {
    id: 'REV-001',
    author: 'Alice Johnson',
    avatarUrl: 'https://placehold.co/40x40.png',
    rating: 5,
    text: 'Absolutely phenomenal experience! The truffle risotto was to die for, and the service was impeccable. GastronomeOS is my new favorite spot!',
    date: '2 days ago',
  },
  {
    id: 'REV-002',
    author: 'Bob Williams',
    avatarUrl: 'https://placehold.co/40x40.png',
    rating: 4,
    text: "Great food and atmosphere. The filet mignon was cooked perfectly. It was a bit busy, so service was a little slow, but overall a fantastic night out. We'll be back.",
    date: '3 days ago',
  },
  {
    id: 'REV-003',
    author: 'Charlie Brown',
    avatarUrl: 'https://placehold.co/40x40.png',
    rating: 3,
    text: "The food was decent, but unfortunately, the Chocolate Lava Cake we wanted was out of stock. It was a bit of a letdown for my wife's birthday. The rest of the meal was okay.",
    date: '1 week ago',
  },
];
